- hosts: localhost
  tasks:
    - name: Install Packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - neovim
        - zsh
        - alacritty
        - tmux
        - nodejs8
        - gcc-c++
        - appeditor
        - pulseaudio-equalizer
        - pavucontrol
      become: yes

    - name: Install Google Chrome
      rpm_key:
        key: https://dl.google.com/linux/linux_signing_key.pub
        state: present
      become: yes

    - zypper:
        name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: present
      become: yes

    - name: Install Sublime Text
      zypper_repository:
        name: sublie-text
        repo: https://download.sublimetext.com/rpm/stable/x86_64/
        auto_import_keys: true
        runrefresh: yes
        state: present
      become: yes

    - package:
        name: sublime-text
        state: present
      become: yes

    - name: Install Zoom
      rpm_key:
        key: https://zoom.us/linux/download/pubkey
        state: present
      become: yes

    - zypper:
        name: https://zoom.us/client/latest/zoom_openSUSE_x86_64.rpm
        state: present
      become: yes

    - name: Create Work and luladjiev directories
      file:
        path: ~/Work/luladjiev
        state: directory
        mode: 0755

    - name: Create Alacritty config folder
      file:
        path: ~/.config/alacritty
        state: directory
        mode: 0755

    - name: Clone dotfiles
      git:
        repo: https://github.com/luladjiev/dotfiles.git
        dest: ~/Work/luladjiev/dotfiles

    - name: Link configurations
      file:
        src: ~/Work/luladjiev/dotfiles/zsh/zshrc
        dest: /home/peter/.zshrc
        state: link

    - file:
        src: ~/Work/luladjiev/dotfiles/fonts.conf
        dest: ~/.fonts.conf
        state: link

    - file:
        src: ~/Work/luladjiev/dotfiles/tmux/tmux.conf
        dest: ~/.tmux.conf
        state: link

    - file:
        src: ~/Work/luladjiev/dotfiles/alacritty/alacritty.yml
        dest: ~/.config/alacritty/alacritty.yml
        state: link

    - name: Get lambda-mod.zsh-theme
      git:
        repo: https://github.com/halfo/lambda-mod-zsh-theme
        dest: /tmp/lambda-mod
    - copy:
        src: /tmp/lambda-mod/lambda-mod.zsh-theme
        dest: ~/.oh-my-zsh/themes/lambda-mod.zsh-theme

    - name: Install FZF
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf

    - script: ~/.fzf/install --all

